runtime: nodejs16

instance_class: F2
resources:
  cpu: 1

network:
  forwarded_ports:
    - 1337/tcp
 
env_variables:
  HOST: '0.0.0.0'
  PORT: 1337
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'eduokitpostgre'
  INSTANCE_CONNECTION_NAME: 'eduokit-363508:europe-southwest1:eduokitpostgre'

beta_settings:
  cloud_sql_instances: eduokit-363508:europe-southwest1:eduokitpostgre'