apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eduobackend
  namespace: '204130050774'
  selfLink: /apis/serving.knative.dev/v1/namespaces/204130050774/services/eduobackend
  uid: 99506ad8-a8ac-420e-b157-2a6e314c0337
  resourceVersion: AAXpgbhayOg
  generation: 5
  creationTimestamp: '2022-09-25T13:35:11.057058Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: fa666696-63df-431e-8686-917de962aee4
    cloud.googleapis.com/location: europe-southwest1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: alpeza06@gmail.com
    serving.knative.dev/lastModifier: alpeza06@gmail.com
    client.knative.dev/user-image: gcr.io/eduokit-363508/eduobackend
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: eduobackend-00004-qoz
      annotations:
        run.googleapis.com/client-name: cloud-run-button
        client.knative.dev/user-image: gcr.io/eduokit-363508/eduobackend
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 204130050774-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/eduokit-363508/eduobackend
        ports:
        - name: http1
          containerPort: 1337
        env:
        - name: HOST
          value: 0.0.0.0
        - name: NODE_ENV
          value: production
        - name: DATABASE_NAME
          value: strapi
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: eduokitpostgre
        - name: INSTANCE_CONNECTION_NAME
          value: eduokitpostgre
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 5
  conditions:
  - type: Ready
    status: 'False'
    reason: HealthCheckContainerError
    message: "Revision 'eduobackend-00004-qoz' is not ready and cannot serve traffic.\
      \ The user-provided container failed to start and listen on the port defined\
      \ provided by the PORT=1337 environment variable. Logs for this revision might\
      \ contain more information.\n\nLogs URL: https://console.cloud.google.com/logs/viewer?project=eduokit-363508&resource=cloud_run_revision/service_name/eduobackend/revision_name/eduobackend-00004-qoz&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22eduobackend%22%0Aresource.labels.revision_name%3D%22eduobackend-00004-qoz%22\
      \ \nFor more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start"
    lastTransitionTime: '2022-09-25T15:03:56.563688Z'
  - type: ConfigurationsReady
    status: 'False'
    reason: HealthCheckContainerError
    message: "The user-provided container failed to start and listen on the port defined\
      \ provided by the PORT=1337 environment variable. Logs for this revision might\
      \ contain more information.\n\nLogs URL: https://console.cloud.google.com/logs/viewer?project=eduokit-363508&resource=cloud_run_revision/service_name/eduobackend/revision_name/eduobackend-00004-qoz&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22eduobackend%22%0Aresource.labels.revision_name%3D%22eduobackend-00004-qoz%22\
      \ \nFor more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start"
    lastTransitionTime: '2022-09-25T15:03:56.440818Z'
  - type: RoutesReady
    status: 'False'
    reason: HealthCheckContainerError
    message: "Revision 'eduobackend-00004-qoz' is not ready and cannot serve traffic.\
      \ The user-provided container failed to start and listen on the port defined\
      \ provided by the PORT=1337 environment variable. Logs for this revision might\
      \ contain more information.\n\nLogs URL: https://console.cloud.google.com/logs/viewer?project=eduokit-363508&resource=cloud_run_revision/service_name/eduobackend/revision_name/eduobackend-00004-qoz&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22eduobackend%22%0Aresource.labels.revision_name%3D%22eduobackend-00004-qoz%22\
      \ \nFor more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start"
    lastTransitionTime: '2022-09-25T15:03:56.563688Z'
  latestCreatedRevisionName: eduobackend-00004-qoz
  traffic:
  - revisionName: eduobackend-00001-qoz
    percent: 100
    latestRevision: true
